/**
 * @file app shell mutation types
 * @author huangyingwen(hyw.huangyingwen@gmail.com)
 */

export const ENABLE_PAGE_TRANSITION = 'ENABLE_PAGE_TRANSITION'
export const DISABLE_PAGE_TRANSITION = 'DISABLE_PAGE_TRANSITION'
export const SET_PAGE_SWITCHING = 'SET_PAGE_SWITCHING'
export const SET_PAGE_TRANSITION_NAME = 'SET_PAGE_TRANSITION_NAME'
export const SET_APP_HEADER = 'SET_APP_HEADER'
export const SET_APP_BOTTOM_NAV = 'SET_APP_BOTTOM_NAV'
export const ACTIVATE_APP_BOTTOM_NAV = 'ACTIVATE_APP_BOTTOM_NAV'
export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY'
export const SAVE_SCROLLTOP = 'SAVE_SCROLLTOP'

export const ENTITIES = 'ENTITIES'
export const ENTITY_REQUEST = 'ENTITY_REQUEST'
export const ENTITY_SUCCESS = 'ENTITY_SUCCESS'
export const ENTITY_FAILURE = 'ENTITY_FAILURE'

export const PAGINATE_REQUEST = 'PAGINATE_REQUEST'
export const PAGINATE_SUCCESS = 'PAGINATE_SUCCESS'
export const PAGINATE_FAILURE = 'PAGINATE_FAILURE'
